-- ============================================================
-- 0005_expand_categories.sql
-- Expand categories to 200+ covering every freelance, trade,
-- local service, and professional occupation.
-- Uses ON CONFLICT (slug) DO NOTHING to prevent duplicates.
-- ============================================================

insert into public.categories (name, slug, icon)
values
  -- ── Technology & Development ──────────────────────────────
  ('Web Development',                'web-development',                'globe'),
  ('Frontend Development',           'frontend-development',           'layout'),
  ('Backend Development',            'backend-development',            'server'),
  ('Full Stack Development',         'full-stack-development',         'layers'),
  ('Mobile App Development',         'mobile-app-development',         'smartphone'),
  ('Android Development',            'android-development',            'smartphone'),
  ('iOS Development',                'ios-development',                'smartphone'),
  ('Software Development',           'software-development',           'code'),
  ('Game Development',               'game-development',               'gamepad'),
  ('AI Engineer',                    'ai-engineer',                    'cpu'),
  ('Machine Learning Engineer',      'machine-learning-engineer',      'brain'),
  ('Data Analyst',                   'data-analyst',                   'bar-chart'),
  ('Data Scientist',                 'data-scientist',                 'activity'),
  ('Database Administrator',         'database-administrator',         'database'),
  ('SQL Developer',                  'sql-developer',                  'database'),
  ('Python Developer',               'python-developer',               'code'),
  ('DevOps Engineer',                'devops-engineer',                'settings'),
  ('Cloud Engineer',                 'cloud-engineer',                 'cloud'),
  ('Cybersecurity Specialist',       'cybersecurity-specialist',       'shield'),
  ('Penetration Tester',             'penetration-tester',             'shield'),
  ('Network Engineer',               'network-engineer',               'wifi'),
  ('IT Support',                     'it-support',                     'headphones'),
  ('Systems Administrator',          'systems-administrator',          'server'),
  ('QA Tester',                      'qa-tester',                      'check-circle'),
  ('Automation Engineer',            'automation-engineer',            'zap'),
  ('Software Testing',               'software-testing',               'bug'),
  ('WordPress Development',          'wordpress-development',          'file-text'),
  ('Shopify Development',            'shopify-development',            'shopping-bag'),
  ('E-commerce',                     'e-commerce',                     'store'),
  ('Blockchain',                     'blockchain',                     'link'),
  ('Data Entry',                     'data-entry',                     'keyboard'),

  -- ── Design & Media ───────────────────────────────────────
  ('Graphic Designer',               'graphic-designer',               'pen-tool'),
  ('Logo Designer',                  'logo-designer',                  'feather'),
  ('UI Designer',                    'ui-designer',                    'palette'),
  ('UX Designer',                    'ux-designer',                    'target'),
  ('UI/UX Design',                   'ui-ux-design',                   'palette'),
  ('Illustrator',                    'illustrator',                    'brush'),
  ('Animator',                       'animator',                       'play-circle'),
  ('Motion Graphics Designer',       'motion-graphics-designer',       'video'),
  ('Video Editor',                   'video-editor',                   'film'),
  ('Photographer',                   'photographer',                   'camera'),
  ('Videographer',                   'videographer',                   'video'),
  ('Audio Producer',                 'audio-producer',                 'headphones'),
  ('Music Producer',                 'music-producer',                 'music'),
  ('Voice Over Artist',              'voice-over-artist',              'mic'),
  ('3D Artist',                      '3d-artist',                      'box'),
  ('3D Modeling',                    '3d-modeling',                    'box'),
  ('3D Printing',                    '3d-printing',                    'printer'),
  ('CAD Designer',                   'cad-designer',                   'ruler'),
  ('Interior Designer',              'interior-designer',              'home'),
  ('Web Design',                     'web-design',                     'monitor'),
  ('App Design',                     'app-design',                     'smartphone'),
  ('Product Design',                 'product-design',                 'package'),
  ('Print Design',                   'print-design',                   'file'),
  ('Packaging Design',               'packaging-design',               'package'),
  ('Branding',                       'branding',                       'award'),
  ('Architecture',                   'architecture',                   'building'),

  -- ── Writing & Content ────────────────────────────────────
  ('Copywriter',                     'copywriter',                     'type'),
  ('Content Writer',                 'content-writer',                 'file-text'),
  ('Ghostwriter',                    'ghostwriter',                    'file-text'),
  ('Blogger',                        'blogger',                        'edit'),
  ('Proofreader',                    'proofreader',                    'check-circle'),
  ('Translator',                     'translator',                     'globe'),
  ('Technical Writer',               'technical-writer',               'book-open'),
  ('Scriptwriting',                  'scriptwriting',                  'film'),
  ('Content Strategy',               'content-strategy',               'target'),

  -- ── Marketing & Sales ────────────────────────────────────
  ('SEO Specialist',                 'seo-specialist',                 'search'),
  ('Digital Marketer',               'digital-marketer',               'trending-up'),
  ('PPC Specialist',                 'ppc-specialist',                 'target'),
  ('Social Media Manager',           'social-media-manager',           'share-2'),
  ('Email Marketer',                 'email-marketer',                 'mail'),
  ('Brand Strategist',               'brand-strategist',               'award'),
  ('App Store Optimization',         'app-store-optimization',         'download'),
  ('Lead Generation',                'lead-generation',                'user-plus'),
  ('Sales Representative',           'sales-representative',           'dollar-sign'),
  ('Sales',                          'sales',                          'dollar-sign'),

  -- ── Business & Consulting ────────────────────────────────
  ('Business Consultant',            'business-consultant',            'briefcase'),
  ('Business Analysis',              'business-analysis',              'clipboard'),
  ('Project Manager',                'project-manager',                'calendar'),
  ('Product Manager',                'product-manager',                'layers'),
  ('HR Consultant',                  'hr-consultant',                  'users'),
  ('Recruiter',                      'recruiter',                      'user-plus'),
  ('Legal Consultant',               'legal-consultant',               'scale'),
  ('Virtual Assistant',              'virtual-assistant',              'user'),
  ('Customer Support',               'customer-support',               'headphones'),

  -- ── Finance & Legal ──────────────────────────────────────
  ('Accountant',                     'accountant',                     'dollar-sign'),
  ('Bookkeeper',                     'bookkeeper',                     'book'),
  ('Financial Advisor',              'financial-advisor',              'trending-up'),
  ('Tax Consultant',                 'tax-consultant',                 'calculator'),
  ('Accounting',                     'accounting',                     'dollar-sign'),
  ('Finance',                        'finance',                        'trending-up'),
  ('Legal Services',                 'legal-services',                 'scale'),
  ('Human Resources',                'human-resources',                'users'),
  ('Recruiting',                     'recruiting',                     'user-plus'),
  ('Procurement',                    'procurement',                    'shopping-cart'),

  -- ── Data & Analytics ─────────────────────────────────────
  ('Data Science',                   'data-science',                   'activity'),
  ('Business Intelligence',          'business-intelligence',          'pie-chart'),
  ('Power BI',                       'power-bi',                       'bar-chart'),
  ('Tableau',                        'tableau',                        'bar-chart'),
  ('Excel',                          'excel',                          'table'),
  ('SQL',                            'sql',                            'database'),
  ('Python',                         'python',                         'code'),
  ('Machine Learning',               'machine-learning',               'brain'),
  ('Artificial Intelligence',        'artificial-intelligence',        'cpu'),
  ('Research',                       'research',                       'search'),

  -- ── Skilled Trades ───────────────────────────────────────
  ('Electrician',                    'electrician',                    'zap'),
  ('Plumber',                        'plumber',                        'droplet'),
  ('Carpenter',                      'carpenter',                      'hammer'),
  ('Bricklayer',                     'bricklayer',                     'building'),
  ('Welder',                         'welder',                         'flame'),
  ('Mechanic',                       'mechanic',                       'wrench'),
  ('Auto Electrician',               'auto-electrician',               'zap'),
  ('Painter',                        'painter',                        'paintbrush'),
  ('Roofer',                         'roofer',                         'home'),
  ('Tiler',                          'tiler',                          'grid'),
  ('Flooring Installer',             'flooring-installer',             'layers'),
  ('Drywall Installer',              'drywall-installer',              'square'),
  ('Handyman',                       'handyman',                       'wrench'),
  ('Locksmith',                      'locksmith',                      'lock'),
  ('CCTV Installer',                 'cctv-installer',                 'camera'),
  ('Solar Installer',                'solar-installer',                'sun'),
  ('Fence Installer',                'fence-installer',                'fence'),
  ('Gate Installer',                 'gate-installer',                 'door-open'),
  ('Pool Builder',                   'pool-builder',                   'droplet'),
  ('Pool Cleaner',                   'pool-cleaner',                   'droplet'),
  ('Irrigation Installer',           'irrigation-installer',           'droplet'),

  -- ── Gardening & Outdoor ──────────────────────────────────
  ('Gardener',                       'gardener',                       'leaf'),
  ('Landscaper',                     'landscaper',                     'trees'),
  ('Lawn Mowing',                    'lawn-mowing',                    'scissors'),
  ('Tree Felling',                   'tree-felling',                   'axe'),
  ('Tree Trimming',                  'tree-trimming',                  'scissors'),
  ('Hedge Trimming',                 'hedge-trimming',                 'scissors'),
  ('Weed Removal',                   'weed-removal',                   'x-circle'),
  ('Garden Maintenance',             'garden-maintenance',             'leaf'),
  ('Garden Design',                  'garden-design',                  'palette'),
  ('Pest Control',                   'pest-control',                   'bug'),

  -- ── Home Services ────────────────────────────────────────
  ('Cleaner',                        'cleaner',                        'sparkles'),
  ('House Cleaner',                  'house-cleaner',                  'home'),
  ('Window Cleaner',                 'window-cleaner',                 'square'),
  ('Carpet Cleaner',                 'carpet-cleaner',                 'layers'),
  ('Upholstery Cleaner',             'upholstery-cleaner',             'sofa'),
  ('Pressure Washing',               'pressure-washing',               'droplet'),
  ('Moving Service',                 'moving-service',                 'truck'),
  ('Furniture Assembly',             'furniture-assembly',             'package'),
  ('Appliance Repair',               'appliance-repair',               'settings'),
  ('TV Mounting',                    'tv-mounting',                    'monitor'),
  ('Air Conditioner Technician',     'air-conditioner-technician',     'thermometer'),
  ('Refrigerator Repair',            'refrigerator-repair',            'thermometer'),
  ('Washing Machine Repair',         'washing-machine-repair',         'settings'),

  -- ── Construction ─────────────────────────────────────────
  ('Builder',                        'builder',                        'hammer'),
  ('General Contractor',             'general-contractor',             'briefcase'),
  ('Civil Engineer',                 'civil-engineer',                 'building'),
  ('Quantity Surveyor',              'quantity-surveyor',              'calculator'),
  ('Site Manager',                   'site-manager',                   'clipboard'),
  ('Demolition',                     'demolition',                     'trash-2'),
  ('Concrete Specialist',            'concrete-specialist',            'square'),
  ('Steel Fabricator',               'steel-fabricator',               'iron'),
  ('Construction',                   'construction',                   'hammer'),
  ('Engineering',                    'engineering',                    'cpu'),
  ('Manufacturing',                  'manufacturing',                  'factory'),

  -- ── Automotive ───────────────────────────────────────────
  ('Car Mechanic',                   'car-mechanic',                   'wrench'),
  ('Motorcycle Mechanic',            'motorcycle-mechanic',            'bike'),
  ('Panel Beater',                   'panel-beater',                   'square'),
  ('Spray Painter',                  'spray-painter',                  'paintbrush'),
  ('Vehicle Detailer',               'vehicle-detailer',               'sparkles'),
  ('Car Wash',                       'car-wash',                       'droplet'),
  ('Mobile Mechanic',                'mobile-mechanic',                'truck'),
  ('Tow Truck',                      'tow-truck',                      'truck'),
  ('Automotive',                     'automotive',                     'car'),

  -- ── Health & Beauty ──────────────────────────────────────
  ('Personal Trainer',               'personal-trainer',               'heart'),
  ('Nutritionist',                   'nutritionist',                   'apple'),
  ('Physiotherapist',                'physiotherapist',                'activity'),
  ('Massage Therapist',              'massage-therapist',              'hand'),
  ('Hairdresser',                    'hairdresser',                    'scissors'),
  ('Barber',                         'barber',                         'scissors'),
  ('Makeup Artist',                  'makeup-artist',                  'sparkles'),
  ('Nail Technician',                'nail-technician',                'hand'),
  ('Beauty Therapist',               'beauty-therapist',               'heart'),
  ('Healthcare',                     'healthcare',                     'heart-pulse'),

  -- ── Education & Tutoring ─────────────────────────────────
  ('Tutor',                          'tutor',                          'book-open'),
  ('Mathematics Tutor',              'mathematics-tutor',              'calculator'),
  ('English Tutor',                  'english-tutor',                  'type'),
  ('Coding Tutor',                   'coding-tutor',                   'code'),
  ('Music Teacher',                  'music-teacher',                  'music'),
  ('Language Teacher',               'language-teacher',               'globe'),
  ('Education & Tutoring',           'education-tutoring',             'graduation-cap'),

  -- ── Pets ─────────────────────────────────────────────────
  ('Dog Walker',                     'dog-walker',                     'heart'),
  ('Pet Groomer',                    'pet-groomer',                    'scissors'),
  ('Pet Sitter',                     'pet-sitter',                     'home'),
  ('Dog Trainer',                    'dog-trainer',                    'award'),
  ('Veterinarian',                   'veterinarian',                   'heart-pulse'),

  -- ── Events & Entertainment ───────────────────────────────
  ('DJ',                             'dj',                             'music'),
  ('MC',                             'mc',                             'mic'),
  ('Wedding Planner',                'wedding-planner',                'heart'),
  ('Event Planner',                  'event-planner',                  'calendar'),
  ('Caterer',                        'caterer',                        'utensils'),
  ('Bartender',                      'bartender',                      'wine'),
  ('Security Guard',                 'security-guard',                 'shield'),

  -- ── Delivery & Transport ─────────────────────────────────
  ('Courier',                        'courier',                        'package'),
  ('Driver',                         'driver',                         'car'),
  ('Truck Driver',                   'truck-driver',                   'truck'),
  ('Removal Service',                'removal-service',                'truck'),
  ('Delivery Driver',                'delivery-driver',                'navigation'),

  -- ── Logistics & Supply Chain ─────────────────────────────
  ('Logistics',                      'logistics',                      'truck'),
  ('Supply Chain Management',        'supply-chain-management',        'link'),

  -- ── Real Estate ──────────────────────────────────────────
  ('Estate Agent',                   'estate-agent',                   'home'),
  ('Property Manager',               'property-manager',               'building'),
  ('Property Valuer',                'property-valuer',                'dollar-sign'),
  ('Real Estate',                    'real-estate',                    'home'),

  -- ── Agriculture ──────────────────────────────────────────
  ('Farm Worker',                    'farm-worker',                    'leaf'),
  ('Livestock Specialist',           'livestock-specialist',           'heart'),
  ('Agricultural Consultant',        'agricultural-consultant',        'briefcase'),
  ('Agriculture',                    'agriculture',                    'leaf'),

  -- ── Telecommunications ───────────────────────────────────
  ('Telecommunications',             'telecommunications',             'signal'),

  -- ── Other / Catch-all ────────────────────────────────────
  ('Consultant',                     'consultant',                     'briefcase'),
  ('Freelancer',                     'freelancer',                     'user'),
  ('Assistant',                      'assistant',                      'user-check'),
  ('Researcher',                     'researcher',                     'search'),
  ('Inspector',                      'inspector',                      'eye'),
  ('Auditor',                        'auditor',                        'check-circle'),
  ('Other',                          'other',                          'more-horizontal')

on conflict (slug) do nothing;
