INSERT INTO public.categories (name, slug, icon) VALUES
-- IT & TECHNOLOGY
('IT Support', 'it-support', 'headphones'),
('Computer Repair', 'computer-repair', 'monitor'),
('Laptop Repair', 'laptop-repair', 'monitor'),
('Desktop Computer Repair', 'desktop-computer-repair', 'monitor'),
('Mac Repair', 'mac-repair', 'monitor'),
('Windows Support', 'windows-support', 'monitor'),
('Software Installation', 'software-installation', 'download'),
('Hardware Installation', 'hardware-installation', 'cpu'),
('Virus Removal', 'virus-removal', 'bug'),
('Data Recovery', 'data-recovery', 'hard-drive'),
('Data Backup', 'data-backup', 'database'),
('Network Setup', 'network-setup', 'wifi'),
('Wi-Fi Installation', 'wifi-installation', 'wifi'),
('Router Configuration', 'router-configuration', 'wifi'),
('Server Administration', 'server-administration', 'server'),
('Cloud Computing', 'cloud-computing', 'cloud'),
('Cybersecurity', 'cybersecurity', 'shield'),
('Penetration Testing', 'penetration-testing', 'shield'),
('Website Security', 'website-security', 'shield'),
('Database Administration', 'database-administration', 'database'),
('Database Development', 'database-development', 'database'),
('Web Development', 'web-development', 'globe'),
('Frontend Development', 'frontend-development', 'code'),
('Backend Development', 'backend-development', 'server'),
('Full Stack Development', 'full-stack-development', 'code'),
('Mobile App Development', 'mobile-app-development', 'smartphone'),
('Android Development', 'android-development', 'smartphone'),
('iOS Development', 'ios-development', 'smartphone'),
('App Design', 'app-design', 'smartphone'),
('Software Development', 'software-development', 'code'),
('API Development', 'api-development', 'link'),
('DevOps', 'devops', 'settings'),
('Cloud Engineering', 'cloud-engineering', 'cloud'),
('AI Services', 'ai-services', 'brain'),
('Artificial Intelligence', 'artificial-intelligence', 'brain'),
('Machine Learning', 'machine-learning', 'brain'),
('Data Science', 'data-science', 'bar-chart'),
('Data Analysis', 'data-analysis', 'bar-chart'),
('Business Intelligence', 'business-intelligence', 'bar-chart'),
('Excel Services', 'excel-services', 'file-text'),
('Power BI', 'power-bi', 'bar-chart'),
('Tableau', 'tableau', 'bar-chart'),
('SQL', 'sql', 'database'),
('Python Development', 'python-development', 'code'),
('Automation', 'automation', 'zap'),
('Blockchain', 'blockchain', 'link'),
('Cryptocurrency Development', 'cryptocurrency-development', 'link'),
('3D Modeling', '3d-modeling', 'box'),
('3D Printing', '3d-printing', 'box'),
('CAD Design', 'cad-design', 'box'),
('Computer-Aided Design', 'computer-aided-design', 'box'),
('Electronics Repair', 'electronics-repair', 'wrench'),
('Phone Repair', 'phone-repair', 'smartphone'),
('Tablet Repair', 'tablet-repair', 'tablet'),
('Printer Repair', 'printer-repair', 'printer'),
('CCTV Installation', 'cctv-installation', 'camera'),
('Access Control', 'access-control', 'lock'),
('Biometric Systems', 'biometric-systems', 'fingerprint'),
('Smart Home Installation', 'smart-home-installation', 'home'),
('GPS Installation', 'gps-installation', 'navigation'),
('POS System Installation', 'pos-system-installation', 'credit-card'),

-- WEB, DESIGN & CREATIVE
('Web Design', 'web-design', 'pen-tool'),
('Website Development', 'website-development', 'code'),
('WordPress', 'wordpress', 'globe'),
('Shopify Development', 'shopify-development', 'shopping-cart'),
('E-commerce Development', 'e-commerce-development', 'shopping-cart'),
('UI/UX Design', 'ui-ux-design', 'palette'),
('Graphic Design', 'graphic-design', 'palette'),
('Logo Design', 'logo-design', 'pen-tool'),
('Branding', 'branding', 'pen-tool'),
('Business Cards', 'business-cards', 'credit-card'),
('Flyer Design', 'flyer-design', 'file'),
('Poster Design', 'poster-design', 'image'),
('Brochure Design', 'brochure-design', 'book-open'),
('Packaging Design', 'packaging-design', 'package'),
('Illustration', 'illustration', 'pen-tool'),
('Animation', 'animation', 'play'),
('3D Animation', '3d-animation', 'play'),
('Video Editing', 'video-editing', 'film'),
('Video Production', 'video-production', 'video'),
('Photography', 'photography', 'camera'),
('Product Photography', 'product-photography', 'camera'),
('Real Estate Photography', 'real-estate-photography', 'camera'),
('Drone Photography', 'drone-photography', 'camera'),
('Drone Videography', 'drone-videography', 'video'),
('Photo Editing', 'photo-editing', 'image'),
('Audio Production', 'audio-production', 'music'),
('Voice Over', 'voice-over', 'mic'),
('Music Production', 'music-production', 'music'),
('Podcast Production', 'podcast-production', 'mic'),
('Copywriting', 'copywriting', 'type'),
('Content Writing', 'content-writing', 'type'),
('Blog Writing', 'blog-writing', 'type'),
('Proofreading', 'proofreading', 'check-circle'),
('Translation', 'translation', 'languages'),
('Transcription', 'transcription', 'type'),
('Data Entry', 'data-entry', 'database'),
('Virtual Assistant', 'virtual-assistant', 'user'),

-- BUSINESS & PROFESSIONAL
('Accounting', 'accounting', 'calculator'),
('Bookkeeping', 'bookkeeping', 'book-open'),
('Payroll Services', 'payroll-services', 'dollar-sign'),
('Tax Services', 'tax-services', 'dollar-sign'),
('Tax Consulting', 'tax-consulting', 'dollar-sign'),
('Financial Consulting', 'financial-consulting', 'trending-up'),
('Business Consulting', 'business-consulting', 'briefcase'),
('Business Analysis', 'business-analysis', 'bar-chart'),
('Business Planning', 'business-planning', 'briefcase'),
('Business Registration', 'business-registration', 'file-text'),
('Company Registration', 'company-registration', 'file-text'),
('Market Research', 'market-research', 'search'),
('Project Management', 'project-management', 'clipboard'),
('Administrative Support', 'administrative-support', 'clipboard'),
('Document Preparation', 'document-preparation', 'file-text'),
('Presentation Design', 'presentation-design', 'monitor'),
('Human Resources', 'human-resources', 'users'),
('Recruitment', 'recruitment', 'user-plus'),
('Career Coaching', 'career-coaching', 'trending-up'),
('CV Writing', 'cv-writing', 'file-text'),
('Resume Writing', 'resume-writing', 'file-text'),
('Interview Coaching', 'interview-coaching', 'message-circle'),
('Legal Services', 'legal-services', 'scale'),
('Legal Consulting', 'legal-consulting', 'scale'),
('Contract Services', 'contract-services', 'file-text'),
('Notary Services', 'notary-services', 'stamp'),
('Insurance Services', 'insurance-services', 'shield'),
('Real Estate Services', 'real-estate-services', 'home'),
('Property Management', 'property-management', 'building'),

-- MARKETING & SALES
('Digital Marketing', 'digital-marketing', 'trending-up'),
('Social Media Marketing', 'social-media-marketing', 'share-2'),
('Facebook Marketing', 'facebook-marketing', 'share-2'),
('Instagram Marketing', 'instagram-marketing', 'share-2'),
('TikTok Marketing', 'tiktok-marketing', 'share-2'),
('Google Ads', 'google-ads', 'target'),
('Facebook Ads', 'facebook-ads', 'target'),
('SEO', 'seo', 'search'),
('Local SEO', 'local-seo', 'map-pin'),
('Email Marketing', 'email-marketing', 'mail'),
('Lead Generation', 'lead-generation', 'users'),
('Sales Consulting', 'sales-consulting', 'trending-up'),
('Telemarketing', 'telemarketing', 'phone'),
('Content Marketing', 'content-marketing', 'file-text'),
('Influencer Marketing', 'influencer-marketing', 'star'),
('Marketing Strategy', 'marketing-strategy', 'target'),
('Public Relations', 'public-relations', 'megaphone'),
('Advertising', 'advertising', 'megaphone'),

-- BUILDING & CONSTRUCTION
('General Building', 'general-building', 'building'),
('Building Contractor', 'building-contractor', 'building'),
('Bricklaying', 'bricklaying', 'brick'),
('Block Laying', 'block-laying', 'brick'),
('Cement Work', 'cement-work', 'hard-hat'),
('Concrete Work', 'concrete-work', 'hard-hat'),
('Foundations', 'foundations', 'hard-hat'),
('Renovations', 'renovations', 'hammer'),
('Home Renovations', 'home-renovations', 'home'),
('Kitchen Renovations', 'kitchen-renovations', 'home'),
('Bathroom Renovations', 'bathroom-renovations', 'home'),
('Construction', 'construction', 'hard-hat'),
('Demolition', 'demolition', 'trash-2'),
('Drywall Installation', 'drywall-installation', 'layers'),
('Ceiling Installation', 'ceiling-installation', 'layers'),
('Partition Installation', 'partition-installation', 'layers'),
('Plastering', 'plastering', 'layers'),
('Rendering', 'rendering', 'layers'),
('Waterproofing', 'waterproofing', 'droplet'),
('Roofing', 'roofing', 'home'),
('Roof Repairs', 'roof-repairs', 'home'),
('Gutter Installation', 'gutter-installation', 'droplet'),
('Gutter Cleaning', 'gutter-cleaning', 'droplet'),
('Tiling', 'tiling', 'grid'),
('Floor Tiling', 'floor-tiling', 'grid'),
('Wall Tiling', 'wall-tiling', 'grid'),
('Flooring', 'flooring', 'layers'),
('Laminate Flooring', 'laminate-flooring', 'layers'),
('Vinyl Flooring', 'vinyl-flooring', 'layers'),
('Wooden Flooring', 'wooden-flooring', 'layers'),
('Carpentry', 'carpentry', 'hammer'),
('Cabinet Making', 'cabinet-making', 'hammer'),
('Custom Furniture', 'custom-furniture', 'hammer'),
('Joinery', 'joinery', 'hammer'),
('Welding', 'welding', 'zap'),
('Steelwork', 'steelwork', 'zap'),
('Metal Fabrication', 'metal-fabrication', 'zap'),
('Glass Installation', 'glass-installation', 'square'),
('Aluminium Installation', 'aluminium-installation', 'square'),
('Window Installation', 'window-installation', 'square'),
('Door Installation', 'door-installation', 'door'),
('Garage Door Installation', 'garage-door-installation', 'door'),
('Paving', 'paving', 'layers'),
('Driveway Installation', 'driveway-installation', 'layers'),
('Concrete Driveways', 'concrete-driveways', 'layers'),
('Fencing', 'fencing', 'fence'),
('Gate Installation', 'gate-installation', 'door'),
('Gate Automation', 'gate-automation', 'zap'),
('Painting', 'painting', 'brush'),
('Interior Painting', 'interior-painting', 'brush'),
('Exterior Painting', 'exterior-painting', 'brush'),
('Wallpaper Installation', 'wallpaper-installation', 'image'),
('Handyman Services', 'handyman-services', 'wrench'),

-- PLUMBING
('Plumbing', 'plumbing', 'droplet'),
('Emergency Plumbing', 'emergency-plumbing', 'droplet'),
('Leak Repairs', 'leak-repairs', 'droplet'),
('Pipe Repairs', 'pipe-repairs', 'droplet'),
('Drain Cleaning', 'drain-cleaning', 'droplet'),
('Blocked Drains', 'blocked-drains', 'droplet'),
('Sewer Repairs', 'sewer-repairs', 'droplet'),
('Toilet Repairs', 'toilet-repairs', 'droplet'),
('Tap Repairs', 'tap-repairs', 'droplet'),
('Shower Installation', 'shower-installation', 'droplet'),
('Bath Installation', 'bath-installation', 'droplet'),
('Water Heater Repair', 'water-heater-repair', 'droplet'),
('Geyser Installation', 'geyser-installation', 'droplet'),
('Geyser Repair', 'geyser-repair', 'droplet'),
('Solar Geyser Installation', 'solar-geyser-installation', 'sun'),
('Water Tank Installation', 'water-tank-installation', 'droplet'),
('Pump Installation', 'pump-installation', 'droplet'),
('Irrigation Plumbing', 'irrigation-plumbing', 'droplet'),

-- ELECTRICAL
('Electrical Services', 'electrical-services', 'zap'),
('Electrician', 'electrician', 'zap'),
('Electrical Repairs', 'electrical-repairs', 'zap'),
('Electrical Installation', 'electrical-installation', 'zap'),
('House Wiring', 'house-wiring', 'zap'),
('Rewiring', 'rewiring', 'zap'),
('DB Board Installation', 'db-board-installation', 'zap'),
('DB Board Repairs', 'db-board-repairs', 'zap'),
('Lighting Installation', 'lighting-installation', 'lightbulb'),
('Indoor Lighting', 'indoor-lighting', 'lightbulb'),
('Outdoor Lighting', 'outdoor-lighting', 'lightbulb'),
('LED Installation', 'led-installation', 'lightbulb'),
('Generator Installation', 'generator-installation', 'zap'),
('Generator Repair', 'generator-repair', 'zap'),
('Inverter Installation', 'inverter-installation', 'zap'),
('Inverter Repair', 'inverter-repair', 'zap'),
('Solar Installation', 'solar-installation', 'sun'),
('Solar Panel Installation', 'solar-panel-installation', 'sun'),
('Solar Repairs', 'solar-repairs', 'sun'),
('Battery Backup', 'battery-backup', 'battery'),
('Electrical Safety Inspection', 'electrical-safety-inspection', 'shield'),

-- SOLAR & RENEWABLE ENERGY
('Solar Maintenance', 'solar-maintenance', 'sun'),
('Solar Battery Installation', 'solar-battery-installation', 'battery'),
('Off-Grid Solar', 'off-grid-solar', 'sun'),
('Solar Geysers', 'solar-geysers', 'sun'),
('Solar Water Heating', 'solar-water-heating', 'sun'),
('Energy Consulting', 'energy-consulting', 'zap'),

-- CLEANING
('House Cleaning', 'house-cleaning', 'sparkles'),
('Deep Cleaning', 'deep-cleaning', 'sparkles'),
('Office Cleaning', 'office-cleaning', 'sparkles'),
('Commercial Cleaning', 'commercial-cleaning', 'sparkles'),
('Industrial Cleaning', 'industrial-cleaning', 'sparkles'),
('Move-In Cleaning', 'move-in-cleaning', 'sparkles'),
('Move-Out Cleaning', 'move-out-cleaning', 'sparkles'),
('Carpet Cleaning', 'carpet-cleaning', 'sparkles'),
('Upholstery Cleaning', 'upholstery-cleaning', 'sparkles'),
('Mattress Cleaning', 'mattress-cleaning', 'sparkles'),
('Window Cleaning', 'window-cleaning', 'sparkles'),
('Pressure Cleaning', 'pressure-cleaning', 'sparkles'),
('Driveway Cleaning', 'driveway-cleaning', 'sparkles'),
('Pool Cleaning', 'pool-cleaning', 'sparkles'),
('Airbnb Cleaning', 'airbnb-cleaning', 'sparkles'),
('Post-Construction Cleaning', 'post-construction-cleaning', 'sparkles'),
('Oven Cleaning', 'oven-cleaning', 'sparkles'),
('Garden Cleanup', 'garden-cleanup', 'sparkles'),

-- GARDENING & OUTDOORS
('Gardening', 'gardening', 'leaf'),
('Garden Maintenance', 'garden-maintenance', 'leaf'),
('Landscaping', 'landscaping', 'trees'),
('Landscape Design', 'landscape-design', 'trees'),
('Lawn Mowing', 'lawn-mowing', 'scissors'),
('Lawn Installation', 'lawn-installation', 'scissors'),
('Lawn Repair', 'lawn-repair', 'scissors'),
('Grass Cutting', 'grass-cutting', 'scissors'),
('Tree Trimming', 'tree-trimming', 'scissors'),
('Tree Removal', 'tree-removal', 'trash-2'),
('Tree Planting', 'tree-planting', 'leaf'),
('Hedge Trimming', 'hedge-trimming', 'scissors'),
('Weed Removal', 'weed-removal', 'trash-2'),
('Irrigation', 'irrigation', 'droplet'),
('Sprinkler Installation', 'sprinkler-installation', 'droplet'),
('Irrigation Repairs', 'irrigation-repairs', 'wrench'),
('Composting', 'composting', 'leaf'),
('Plant Care', 'plant-care', 'leaf'),
('Nursery Services', 'nursery-services', 'leaf'),
('Outdoor Maintenance', 'outdoor-maintenance', 'home'),

-- AUTOMOTIVE
('Automotive Services', 'automotive-services', 'car'),
('Car Mechanic', 'car-mechanic', 'car'),
('Mobile Mechanic', 'mobile-mechanic', 'car'),
('Motorcycle Repair', 'motorcycle-repair', 'bike'),
('Scooter Repair', 'scooter-repair', 'bike'),
('Auto Electrical', 'auto-electrical', 'zap'),
('Car Diagnostics', 'car-diagnostics', 'search'),
('Engine Repair', 'engine-repair', 'wrench'),
('Brake Repair', 'brake-repair', 'disc'),
('Clutch Repair', 'clutch-repair', 'wrench'),
('Gearbox Repair', 'gearbox-repair', 'wrench'),
('Suspension Repair', 'suspension-repair', 'wrench'),
('Exhaust Repair', 'exhaust-repair', 'wrench'),
('Air Conditioning Repair', 'air-conditioning-repair', 'snowflake'),
('Battery Replacement', 'battery-replacement', 'battery'),
('Car Battery Services', 'car-battery-services', 'battery'),
('Tyre Services', 'tyre-services', 'circle'),
('Wheel Alignment', 'wheel-alignment', 'circle'),
('Wheel Balancing', 'wheel-balancing', 'circle'),
('Puncture Repair', 'puncture-repair', 'circle'),
('Car Wash', 'car-wash', 'droplet'),
('Mobile Car Wash', 'mobile-car-wash', 'droplet'),
('Car Detailing', 'car-detailing', 'sparkles'),
('Interior Car Cleaning', 'interior-car-cleaning', 'sparkles'),
('Vehicle Polishing', 'vehicle-polishing', 'sparkles'),
('Vehicle Wrapping', 'vehicle-wrapping', 'package'),
('Window Tinting', 'window-tinting', 'square'),
('Dent Repair', 'dent-repair', 'wrench'),
('Panel Beating', 'panel-beating', 'wrench'),
('Spray Painting', 'spray-painting', 'brush'),
('Auto Glass', 'auto-glass', 'square'),
('Windscreen Repair', 'windscreen-repair', 'square'),
('Windscreen Replacement', 'windscreen-replacement', 'square'),
('Vehicle Recovery', 'vehicle-recovery', 'truck'),
('Towing', 'towing', 'truck'),
('Roadside Assistance', 'roadside-assistance', 'phone'),
('Car Inspection', 'car-inspection', 'search'),
('Vehicle Tracking Installation', 'vehicle-tracking-installation', 'navigation'),

-- MOVING & DELIVERY
('Moving Services', 'moving-services', 'truck'),
('House Moving', 'house-moving', 'truck'),
('Office Moving', 'office-moving', 'truck'),
('Furniture Moving', 'furniture-moving', 'truck'),
('Packing Services', 'packing-services', 'package'),
('Unpacking Services', 'unpacking-services', 'package'),
('Man and Van', 'man-and-van', 'truck'),
('Courier Services', 'courier-services', 'truck'),
('Local Delivery', 'local-delivery', 'map-pin'),
('Furniture Delivery', 'furniture-delivery', 'truck'),
('Appliance Delivery', 'appliance-delivery', 'truck'),
('Same-Day Delivery', 'same-day-delivery', 'clock'),
('Parcel Delivery', 'parcel-delivery', 'package'),
('Truck Hire', 'truck-hire', 'truck'),
('Trailer Hire', 'trailer-hire', 'truck'),
('Removal Services', 'removal-services', 'truck'),
('Storage Services', 'storage-services', 'archive'),

-- SECURITY
('Security Services', 'security-services', 'shield'),
('Security Guard', 'security-guard', 'shield'),
('Armed Response', 'armed-response', 'shield'),
('Security Assessment', 'security-assessment', 'shield'),
('CCTV Repair', 'cctv-repair', 'camera'),
('Alarm Installation', 'alarm-installation', 'bell'),
('Alarm Repair', 'alarm-repair', 'bell'),
('Electric Fence Installation', 'electric-fence-installation', 'zap'),
('Electric Fence Repair', 'electric-fence-repair', 'zap'),
('Gate Security', 'gate-security', 'shield'),
('Intercom Installation', 'intercom-installation', 'phone'),
('Biometric Access', 'biometric-access', 'fingerprint'),
('Security Patrol', 'security-patrol', 'eye'),
('Private Security', 'private-security', 'shield'),
('Event Security', 'event-security', 'shield'),

-- HOME SERVICES
('Furniture Assembly', 'furniture-assembly', 'hammer'),
('Appliance Installation', 'appliance-installation', 'wrench'),
('Appliance Repair', 'appliance-repair', 'wrench'),
('Washing Machine Repair', 'washing-machine-repair', 'wrench'),
('Dishwasher Repair', 'dishwasher-repair', 'wrench'),
('Fridge Repair', 'fridge-repair', 'wrench'),
('Freezer Repair', 'freezer-repair', 'wrench'),
('Oven Repair', 'oven-repair', 'wrench'),
('Stove Repair', 'stove-repair', 'wrench'),
('Microwave Repair', 'microwave-repair', 'wrench'),
('Air Conditioner Installation', 'air-conditioner-installation', 'wind'),
('Air Conditioner Repair', 'air-conditioner-repair', 'wind'),
('Air Conditioner Servicing', 'air-conditioner-servicing', 'wind'),
('Pest Control', 'pest-control', 'bug'),
('Fumigation', 'fumigation', 'bug'),
('Locksmith', 'locksmith', 'lock'),
('Key Cutting', 'key-cutting', 'key'),
('Garage Door Repair', 'garage-door-repair', 'wrench'),
('Curtain Installation', 'curtain-installation', 'home'),
('Blind Installation', 'blind-installation', 'home'),
('Interior Decorating', 'interior-decorating', 'palette'),
('Home Organization', 'home-organization', 'box'),
('Home Maintenance', 'home-maintenance', 'wrench'),

-- PERSONAL SERVICES
('Personal Trainer', 'personal-trainer', 'heart'),
('Fitness Coaching', 'fitness-coaching', 'heart'),
('Nutrition Coaching', 'nutrition-coaching', 'heart'),
('Life Coaching', 'life-coaching', 'heart'),
('Personal Development', 'personal-development', 'trending-up'),
('Hairdresser', 'hairdresser', 'scissors'),
('Barber', 'barber', 'scissors'),
('Makeup Artist', 'makeup-artist', 'palette'),
('Nail Technician', 'nail-technician', 'heart'),
('Beauty Therapist', 'beauty-therapist', 'heart'),
('Massage Therapist', 'massage-therapist', 'hand'),
('Tattoo Artist', 'tattoo-artist', 'pen-tool'),
('Personal Shopper', 'personal-shopper', 'shopping-bag'),
('Tailor', 'tailor', 'scissors'),
('Clothing Alterations', 'clothing-alterations', 'scissors'),
('Sewing', 'sewing', 'scissors'),
('Dressmaking', 'dressmaking', 'scissors'),

-- CHILDREN & FAMILY
('Babysitting', 'babysitting', 'heart'),
('Childcare', 'childcare', 'heart'),
('Nanny Services', 'nanny-services', 'heart'),
('Au Pair Services', 'au-pair-services', 'heart'),
('Child Tutoring', 'child-tutoring', 'graduation-cap'),
('School Tutoring', 'school-tutoring', 'graduation-cap'),
('Homework Assistance', 'homework-assistance', 'graduation-cap'),
('Special Needs Tutoring', 'special-needs-tutoring', 'graduation-cap'),
('Music Lessons', 'music-lessons', 'music'),
('Art Lessons', 'art-lessons', 'palette'),
('Sports Coaching', 'sports-coaching', 'activity'),
('Swimming Lessons', 'swimming-lessons', 'droplet'),

-- EDUCATION
('Academic Tutoring', 'academic-tutoring', 'graduation-cap'),
('Mathematics Tutoring', 'mathematics-tutoring', 'graduation-cap'),
('Science Tutoring', 'science-tutoring', 'graduation-cap'),
('English Tutoring', 'english-tutoring', 'graduation-cap'),
('Afrikaans Tutoring', 'afrikaans-tutoring', 'graduation-cap'),
('Accounting Tutoring', 'accounting-tutoring', 'graduation-cap'),
('Computer Lessons', 'computer-lessons', 'monitor'),
('Programming Lessons', 'programming-lessons', 'code'),
('Coding Lessons', 'coding-lessons', 'code'),
('IT Training', 'it-training', 'monitor'),
('Business Training', 'business-training', 'briefcase'),
('Language Lessons', 'language-lessons', 'languages'),
('Exam Preparation', 'exam-preparation', 'book-open'),
('Online Tutoring', 'online-tutoring', 'monitor'),
('Guitar Lessons', 'guitar-lessons', 'music'),
('Piano Lessons', 'piano-lessons', 'music'),
('Driving Lessons', 'driving-lessons', 'car'),

-- EVENTS
('Event Planning', 'event-planning', 'calendar'),
('Wedding Planning', 'wedding-planning', 'calendar'),
('Party Planning', 'party-planning', 'calendar'),
('Event Catering', 'event-catering', 'utensils'),
('Wedding Catering', 'wedding-catering', 'utensils'),
('Private Catering', 'private-catering', 'utensils'),
('Bartending Services', 'bartending-services', 'wine'),
('DJ Services', 'dj-services', 'music'),
('Live Music', 'live-music', 'music'),
('Band Services', 'band-services', 'music'),
('Event Photography', 'event-photography', 'camera'),
('Event Videography', 'event-videography', 'video'),
('Wedding Photography', 'wedding-photography', 'camera'),
('Wedding Videography', 'wedding-videography', 'video'),
('Decor Services', 'decor-services', 'sparkles'),
('Event Decorations', 'event-decorations', 'sparkles'),
('Balloon Decorations', 'balloon-decorations', 'sparkles'),
('Wedding Decorations', 'wedding-decorations', 'sparkles'),
('Sound and Lighting', 'sound-and-lighting', 'volume-2'),
('Equipment Hire', 'equipment-hire', 'package'),
('Marquee Hire', 'marquee-hire', 'package'),
('Furniture Hire', 'furniture-hire', 'package'),
('Party Equipment Hire', 'party-equipment-hire', 'package'),
('MC Services', 'mc-services', 'mic'),
('Entertainment', 'entertainment', 'music'),

-- FOOD
('Catering', 'catering', 'utensils'),
('Private Chef', 'private-chef', 'chef-hat'),
('Personal Chef', 'personal-chef', 'chef-hat'),
('Meal Preparation', 'meal-preparation', 'chef-hat'),
('Baking', 'baking', 'cake'),
('Cake Making', 'cake-making', 'cake'),
('Wedding Cakes', 'wedding-cakes', 'cake'),
('Birthday Cakes', 'birthday-cakes', 'cake'),
('Pastry', 'pastry', 'cake'),
('Food Delivery', 'food-delivery', 'truck'),
('Meal Delivery', 'meal-delivery', 'truck'),
('Braai Catering', 'braai-catering', 'utensils'),
('Corporate Catering', 'corporate-catering', 'utensils'),

-- PETS & ANIMALS
('Pet Sitting', 'pet-sitting', 'heart'),
('Dog Walking', 'dog-walking', 'heart'),
('Dog Grooming', 'dog-grooming', 'heart'),
('Pet Grooming', 'pet-grooming', 'heart'),
('Pet Training', 'pet-training', 'heart'),
('Dog Training', 'dog-training', 'heart'),
('Pet Boarding', 'pet-boarding', 'heart'),
('Pet Taxi', 'pet-taxi', 'heart'),
('Veterinary Services', 'veterinary-services', 'heart'),
('Animal Care', 'animal-care', 'heart'),
('Farm Animal Care', 'farm-animal-care', 'heart'),

-- AGRICULTURE & FARMING
('Farming', 'farming', 'sprout'),
('Farm Maintenance', 'farm-maintenance', 'wrench'),
('Livestock Services', 'livestock-services', 'heart'),
('Poultry Services', 'poultry-services', 'heart'),
('Agricultural Consulting', 'agricultural-consulting', 'briefcase'),
('Agricultural Equipment Repair', 'agricultural-equipment-repair', 'wrench'),
('Tractor Repair', 'tractor-repair', 'wrench'),
('Farm Fencing', 'farm-fencing', 'fence'),

-- PROFESSIONAL CREATIVE SERVICES
('Interior Design', 'interior-design', 'palette'),
('Landscape Architecture', 'landscape-architecture', 'trees'),
('Product Design', 'product-design', 'box'),
('Industrial Design', 'industrial-design', 'box'),
('Furniture Design', 'furniture-design', 'box'),
('Fashion Design', 'fashion-design', 'scissors'),
('Jewelry Design', 'jewelry-design', 'gem'),
('Textile Design', 'textile-design', 'scissors'),

-- OTHER LOCAL SERVICES
('Errand Services', 'errand-services', 'navigation'),
('Personal Assistant', 'personal-assistant', 'user'),
('Shopping Services', 'shopping-services', 'shopping-bag'),
('Queue Services', 'queue-services', 'users'),
('Elderly Assistance', 'elderly-assistance', 'heart'),
('Home Assistance', 'home-assistance', 'home'),
('Senior Care', 'senior-care', 'heart'),
('Disability Assistance', 'disability-assistance', 'heart'),
('Interpretation', 'interpretation', 'languages'),
('Recycling', 'recycling', 'refresh-cw'),
('Waste Removal', 'waste-removal', 'trash-2'),
('Rubbish Removal', 'rubbish-removal', 'trash-2'),
('Scrap Removal', 'scrap-removal', 'trash-2'),
('Junk Removal', 'junk-removal', 'trash-2'),
('Equipment Rental', 'equipment-rental', 'package'),
('Tool Rental', 'tool-rental', 'package'),
('Machinery Rental', 'machinery-rental', 'package'),
('General Labour', 'general-labour', 'wrench'),
('Temporary Labour', 'temporary-labour', 'wrench'),
('Event Staff', 'event-staff', 'users'),
('Other Services', 'other-services', 'more-horizontal')
ON CONFLICT (slug) DO NOTHING;